__title__ = 'pyfa'
__description__ = 'FurAffinity wrapper for python.'
__url__ = 'https://github.com/rorre/FurAffinity-Python'
__version__ = '0.0.1'
__author__ = 'Rendy Arya Kemal'
__author_email__ = 'rendyarya22@gmail.com'